name: Check card priority and Set status

on:
  issues:
    types:
      - opened

jobs:
  Set_Status_by_Priority:
    runs-on: ubuntu-latest
    
    steps:
      - run: echo '${{ toJSON(github.event) }}'
