name: Update Projects

on:
  issues:
    types:
      - opened
      - labeled
      
jobs:
  issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Check if label contains High
        id: check-result
        uses: actions/github-script@v6
        with:
          script: |
            const labels = github.rest.issues.listLabelsOnIssue({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number
              });
            console.log(labels[0].name);
            return labels.includes("High")
      
      - name: Change Fields Value
        if: ${{steps.check-result.outputs.result == 'True'}}
        uses: EndBug/project-fields@v1.0.1
        with:
          fields: Status,Priority
          github_token: ${{ secrets.SOME_TOKEN }}
          project_url: https://github.com/users/usa0w0/projects/5
          values: やらなきゃ😭,High
      
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.removeLabel({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: "High"
            })
