name: Update Projects

on:
  issues:
    types:
      - labeled

concurrency:
  group: update-projects-${{ github.event_name }}
  cancel-in-progress: true


jobs:
  issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      # substitute RELEASE_VERSION for the latest version available in releases
      - uses: Machine-Maker/add-to-project-action@v0.2.0
        with:
          github-token: ${{ secrets.SOME_TOKEN }}
          project-url: https://github.com/users/usa0w0/projects/5/views/1
          column-field: Status
          label-to-column-map: |
            {
              "High": "やらなきゃ😭"
            }
      - uses: Machine-Maker/add-to-project-action@v0.2.0
        with:
          github-token: ${{ secrets.SOME_TOKEN }}
          project-url: https://github.com/users/usa0w0/projects/5/views/1
          column-field: Priority
          label-to-column-map: |
            {
              "High": "High"
            }
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.removeLabel({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: High
            })
